import { BaseApp, attachActions } from "./base-app.js";
import { Compat } from "../compat.js";
import { StoryStore } from "../store.js";
import { AmbientAudio } from "../audio.js";
import { SYSTEM_ID } from "../constants.js";
import { clone, escapeHTML, uid } from "../utils.js";

export class StoryTools extends BaseApp {
  static DEFAULT_OPTIONS={id:"mr-story-tools",tag:"section",window:{title:"MR.Tools.Title",resizable:true},position:{width:1040,height:740},classes:["mr-app","mr-tools"]};
  constructor(options={}){super(options);this.section=options.section??"relationships";this._unsubscribe=StoryStore.subscribe(()=>this.render())}
  async close(options){this._unsubscribe?.();return super.close(options)}
  async _prepareContext(){const characters=game.actors?.filter(a=>a.type==="character")??[],positions=StoryStore.story?.relationshipPositions??{};const nodes=characters.map((actor,index)=>({actor,x:positions[actor.id]?.x??18+(index%4)*22,y:positions[actor.id]?.y??24+Math.floor(index/4)*35}));const nodeMap=Object.fromEntries(nodes.map(n=>[n.actor.id,n]));const relations=(StoryStore.story?.relationships??[]).map(r=>({...r,source:nodeMap[r.sourceId],target:nodeMap[r.targetId]})).filter(r=>r.source&&r.target);return{section:this.section,story:StoryStore.story,characters,nodes,relations,archive:game.settings.get(SYSTEM_ID,"storyArchive")??[],custom:game.settings.get(SYSTEM_ID,"customContent"),safety:game.settings.get(SYSTEM_ID,"safetyState"),isGM:Compat.isGM(),audioCurrent:AmbientAudio.current}}
  async _renderHTML(context){return Compat.renderTemplate("systems/mr-story-night/templates/story-tools.hbs",context)}
  _replaceHTML(result,content){const wrapper=document.createElement("div");wrapper.innerHTML=result;content.replaceChildren(...wrapper.childNodes);attachActions(content,this);this._bind(content)}
  activateListeners(html){super.activateListeners?.(html);const root=html[0]??html;attachActions(root,this);this._bind(root)}
  _bind(root){root.querySelectorAll("[data-section]").forEach(el=>el.addEventListener("click",()=>{this.section=el.dataset.section;this.render()}));root.querySelectorAll(".mr-relation-node").forEach(el=>this._dragNode(el,root));root.querySelector("[name=story-pack]")?.addEventListener("change",async event=>{const file=event.target.files?.[0];if(!file)return;try{await game[SYSTEM_ID].importStory(await file.text());Compat.notify("info",game.i18n.localize("MR.Archive.Imported"));this.render()}catch(error){Compat.notify("error",error.message)}})}
  _dragNode(node,root){node.addEventListener("pointerdown",event=>{if(!Compat.isGM())return;node.setPointerCapture(event.pointerId);const board=root.querySelector(".mr-relation-board"),rect=board.getBoundingClientRect();const move=e=>{node.style.left=`${Math.max(5,Math.min(90,(e.clientX-rect.left)/rect.width*100))}%`;node.style.top=`${Math.max(8,Math.min(88,(e.clientY-rect.top)/rect.height*100))}%`};const up=async()=>{node.removeEventListener("pointermove",move);const positions={...(StoryStore.story.relationshipPositions??{}),[node.dataset.actorId]:{x:parseFloat(node.style.left),y:parseFloat(node.style.top)}};await StoryStore.patch({relationshipPositions:positions});};node.addEventListener("pointermove",move);node.addEventListener("pointerup",up,{once:true})})}
  async _onAction(event,action){event.preventDefault();const root=event.currentTarget.closest(".mr-tools-shell")??document;
    if(action==="add-relation"){const source=root.querySelector("[name=source]")?.value,target=root.querySelector("[name=target]")?.value,kind=root.querySelector("[name=kind]")?.value,detail=root.querySelector("[name=detail]")?.value;if(!source||!target||source===target)return;const relationship={id:uid(),sourceId:source,targetId:target,kind,detail};return StoryStore.patch({relationships:[...(StoryStore.story.relationships??[]),relationship]},{type:"relationship",label:detail||kind})}
    if(action==="delete-relation")return StoryStore.patch({relationships:StoryStore.story.relationships.filter(r=>r.id!==event.currentTarget.dataset.id)});
    if(action==="restore-story"){const story=(game.settings.get(SYSTEM_ID,"storyArchive")??[]).find(x=>x.id===event.currentTarget.dataset.id);if(story&&await Compat.confirm({title:game.i18n.localize("MR.Archive.Restore"),content:`<p>${escapeHTML(story.title)}</p>`}))return StoryStore.replace(story)}
    if(action==="export-story"){const blob=new Blob([game[SYSTEM_ID].exportStory()],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${StoryStore.story.title.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}.mrstory.json`;a.click();URL.revokeObjectURL(a.href);return}
    if(action==="save-content"){const custom={prompts:root.querySelector("[name=prompts]").value.split("\n").map(x=>x.trim()).filter(Boolean),complications:root.querySelector("[name=complications]").value.split("\n").map(x=>x.trim()).filter(Boolean)};await game.settings.set(SYSTEM_ID,"customContent",custom);return Compat.notify("info",game.i18n.localize("MR.Content.Saved"))}
    if(action==="save-safety"){const state=clone(game.settings.get(SYSTEM_ID,"safetyState"));state.lines=root.querySelector("[name=lines]").value.split("\n").filter(Boolean);state.veils=root.querySelector("[name=veils]").value.split("\n").filter(Boolean);await game.settings.set(SYSTEM_ID,"safetyState",state);return this.render()}
    if(action==="safety-signal"){const signal={id:uid(),type:event.currentTarget.dataset.signal,at:Date.now()};if(!Compat.isGM()){game.socket.emit(`system.${SYSTEM_ID}`,{type:"safety-request",signal});Compat.notify("info",game.i18n.localize("MR.Safety.Sent"));return}const state=clone(game.settings.get(SYSTEM_ID,"safetyState"));state.signals.push(signal);state.signals=state.signals.slice(-20);if(signal.type==="pause")state.paused=true;await game.settings.set(SYSTEM_ID,"safetyState",state);document.documentElement.classList.toggle("mr-safety-paused",state.paused);Compat.notify("warn",game.i18n.localize(`MR.Safety.Signal.${signal.type}`));game.socket.emit(`system.${SYSTEM_ID}`,{type:"safety",state});return this.render()}
    if(action==="resume"){const state=clone(game.settings.get(SYSTEM_ID,"safetyState"));state.paused=false;await game.settings.set(SYSTEM_ID,"safetyState",state);document.documentElement.classList.remove("mr-safety-paused");game.socket.emit(`system.${SYSTEM_ID}`,{type:"safety",state});return this.render()}
    if(action==="audio-play"){await AmbientAudio.play(event.currentTarget.dataset.theme);return this.render()}
    if(action==="audio-stop"){AmbientAudio.stop();return this.render()}
    if(action==="print-finale")return window.print();
  }
}
